# Code generated by Arduino Runtime for MicroPython
from arduino import *

def setup():
  # your initialization code goes here
  # this code only runs once at start
  print('setup')

def loop():
  # code that needs to run repeatedly goes here
  print('loop')
  delay(1000)

def cleanup():
  # code to cleanup or reset things when the program stops goes here
  print('cleanup')

# start your program
start(setup, loop, cleanup)